### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by ijosue16**
first commit of html

### CODE REVIEW

**Comment by ace2016** [comment]
Give me few minutes, I’m trying to eat

**Comment by ijosue16** [comment]
tell me when you are done

**Comment by ace2016** [comment]
Let's use google meet
I will use my iPad
Owhofasa Mobo has invited you to join a video meeting on Google Meet.

Join the meeting: https://meet.google.com/kxx-ceqc-fii

**Comment by ace2016** [comment]
Hello,

Are you still there?

**Pull request closed without merging**
